proj1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace proj1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        //about page
        public ActionResult About()
        {

            return View();
        }

        public string WelcomeMsg(string input)
        {
            if (!String.IsNullOrEmpty(input))
                return "Thank you  " + input + " for visit our site";
            else
                return "Please enter your name.";
        }

    }


}

proj1/Controllers/HotelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using proj1.DAL;
using proj1.Models;

namespace proj1.Controllers
{
    public class HotelsController : Controller
    {
        private WebContext db = new WebContext();

        // GET: Hotels 

        
        public ActionResult Index(String searchHotelCity, String searchHotelName, String searchHotelRating)
        {
            var hotel = from m in db.hotels select m;           //Extended Search by topic

            if (!String.IsNullOrEmpty(searchHotelCity))        // search hotel by city
            {
                hotel = hotel.Where(s => s.hotelCity.Contains(searchHotelCity));
            }
            if (!String.IsNullOrEmpty(searchHotelName))         // search hotel by name
            {
                hotel = hotel.Where(s => s.hotelName.Contains(searchHotelName));
            }
            if (!String.IsNullOrEmpty(searchHotelRating))        // search hotel by rating
            {
                hotel = hotel.Where(s => s.hotelRating.Contains(searchHotelRating));
            }
            {
            }
        
            return View(hotel);
        }


        // GET: Hotels/Details/5     
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotel hotel = db.hotels.Find(id);
            if (hotel == null)
            {
                return HttpNotFound();
            }
            return View(hotel);
        }

        // GET: Hotels/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Hotels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,hotelName,hotelCity,hotelAddress,hotelRating,hotelPrice,Wifi,hotelTransportation,imghotel1,imghotel2,imghotel3,imghotel4,imghotel5,hotelInfo")] Hotel hotel)
        {
            if (ModelState.IsValid)
            {
                db.hotels.Add(hotel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(hotel);
        }

        // GET: Hotels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotel hotel = db.hotels.Find(id);
            if (hotel == null)
            {
                return HttpNotFound();
            }
            return View(hotel);
        }

        // POST: Hotels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,hotelName,hotelCity,hotelAddress,hotelRating,hotelPrice,Wifi,hotelTransportation,imghotel1,imghotel2,imghotel3,imghotel4,imghotel5,hotelInfo")] Hotel hotel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hotel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hotel);
        }

        // GET: Hotels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotel hotel = db.hotels.Find(id);
            if (hotel == null)
            {
                return HttpNotFound();
            }
            return View(hotel);
        }

        // POST: Hotels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Hotel hotel = db.hotels.Find(id);
            db.hotels.Remove(hotel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        //getAddress - google maps, places
        public ActionResult getAddress()
        {
            List<String> address = new List<string>();
            var hotels = from n in db.hotels select n;
            foreach (var item in hotels)
            {
                if (item.hotelAddress != null)
                {
                    address.Add(item.hotelAddress);
                }
            }

            return Json(address, JsonRequestBehavior.AllowGet);
        }
      
    }
}

proj1/Controllers/RecommendationHotelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using proj1.DAL;
using proj1.Models;

namespace proj1.Controllers
{
    public class RecommendationHotelsController : Controller
    {
        private WebContext db = new WebContext();

        // GET: RecommendationHotels
        public ActionResult Index(String city)
        {
            var recommendationsHotel = db.RecommendationsHotel.Include(r => r.hotel);
            if (!String.IsNullOrEmpty(city))        // search by city
            {
                recommendationsHotel = recommendationsHotel.Where(s => s.hotel.hotelCity.Contains(city));
            }
            return View(recommendationsHotel.ToList());
        }

        // GET: RecommendationHotels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RecommendationHotel recommendationHotel = db.RecommendationsHotel.Find(id);
            if (recommendationHotel == null)
            {
                return HttpNotFound();
            }
            return View(recommendationHotel);
        }

        // GET: RecommendationHotels/Create
        public ActionResult Create()
        {
            ViewBag.HotelID = new SelectList(db.hotels, "ID", "hotelName");
            return View();
        }

        // POST: RecommendationHotels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,HotelID,recoName,recoPhone,recoRating,recoInfo")] RecommendationHotel recommendationHotel)
        {
            if (ModelState.IsValid)
            {
                db.RecommendationsHotel.Add(recommendationHotel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.HotelID = new SelectList(db.hotels, "ID", "hotelName", recommendationHotel.HotelID);
            return View(recommendationHotel);
        }

        // GET: RecommendationHotels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RecommendationHotel recommendationHotel = db.RecommendationsHotel.Find(id);
            if (recommendationHotel == null)
            {
                return HttpNotFound();
            }
            ViewBag.HotelID = new SelectList(db.hotels, "ID", "hotelName", recommendationHotel.HotelID);   
            return View(recommendationHotel);
        }

        // POST: RecommendationHotels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,HotelID,recoName,recoPhone,recoRating,recoInfo")] RecommendationHotel recommendationHotel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(recommendationHotel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.HotelID = new SelectList(db.hotels, "ID", "hotelName", recommendationHotel.HotelID);
            return View(recommendationHotel);
        }

        // GET: RecommendationHotels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RecommendationHotel recommendationHotel = db.RecommendationsHotel.Find(id);
            if (recommendationHotel == null)
            {
                return HttpNotFound();
            }
            return View(recommendationHotel);
        }

        // POST: RecommendationHotels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RecommendationHotel recommendationHotel = db.RecommendationsHotel.Find(id);
            db.RecommendationsHotel.Remove(recommendationHotel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

proj1/Controllers/RecommendationRestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using proj1.DAL;
using proj1.Models;

namespace proj1.Controllers
{
    public class RecommendationRestsController : Controller
    {
        private WebContext db = new WebContext();

        // GET: RecommendationRests
        public ActionResult Index(String city)
        {
            var recommendationsRest = db.RecommendationsRest.Include(r => r.rest);
            if (!String.IsNullOrEmpty(city))        // search by city
            {
                recommendationsRest = recommendationsRest.Where(s => s.rest.restCity.Contains(city));
            }
            return View(recommendationsRest.ToList());
        }

        // GET: RecommendationRests/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RecommendationRest recommendationRest = db.RecommendationsRest.Find(id);
            if (recommendationRest == null)
            {
                return HttpNotFound();
            }
            return View(recommendationRest);
        }

        // GET: RecommendationRests/Create
        public ActionResult Create()
        {
            ViewBag.RestID = new SelectList(db.rests, "ID", "restName");
            return View();
        }

        // POST: RecommendationRests/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,RestID,recoName,recoPhone,recoRating,recoInfo")] RecommendationRest recommendationRest)
        {
            if (ModelState.IsValid)
            {
                db.RecommendationsRest.Add(recommendationRest);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.RestID = new SelectList(db.rests, "ID", "restName", recommendationRest.RestID);
            return View(recommendationRest);
        }

        // GET: RecommendationRests/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RecommendationRest recommendationRest = db.RecommendationsRest.Find(id);
            if (recommendationRest == null)
            {
                return HttpNotFound();
            }
            ViewBag.RestID = new SelectList(db.rests, "ID", "restName", recommendationRest.RestID);
            return View(recommendationRest);
        }

        // POST: RecommendationRests/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,RestID,recoName,recoPhone,recoRating,recoInfo")] RecommendationRest recommendationRest)
        {
            if (ModelState.IsValid)
            {
                db.Entry(recommendationRest).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.RestID = new SelectList(db.rests, "ID", "restName", recommendationRest.RestID);
            return View(recommendationRest);
        }

        // GET: RecommendationRests/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RecommendationRest recommendationRest = db.RecommendationsRest.Find(id);
            if (recommendationRest == null)
            {
                return HttpNotFound();
            }
            return View(recommendationRest);
        }

        // POST: RecommendationRests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RecommendationRest recommendationRest = db.RecommendationsRest.Find(id);
            db.RecommendationsRest.Remove(recommendationRest);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

proj1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<!DOCTYPE html>
    <head>
        <meta charset="utf-8">
        <title>About page</title>
        <link rel="stylesheet" href="~/Content/bootstrap.min.css">
        <link rel="stylesheet" href="~/Content/icomoon-social.css">
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,600,800' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="~/Content/leaflet.css" />
        <link rel="stylesheet" href="~/Content/styleContact.css" type="text/css" media="all" />
        <link rel="stylesheet" href="~/Content/main.css">
        <script src="~/js/modernizr-2.6.2-respond-1.1.0.min.js"></script>
    </head>

<canvas id="myCanvas" width="300" height="250"></canvas>
<script>
    var canvas = document.getElementById('myCanvas');
    var context = canvas.getContext('2d');
    var imageObj = new Image();

    imageObj.onload = function () {
        context.drawImage(imageObj, 69, 50);
    };
    imageObj.src = 'http://streamlineinternetmarketing.com/wp-content/uploads/2015/05/about_image.jpg';
</script>


<p id="rData">
</p>
<p>
    Enter you name @Html.TextBox("Name")
    <input type="submit" id="SubmitName" value="Submit" />
</p>



@section Scripts{
<script type="text/jscript">
    $('#SubmitName').click(function () {
        var url = "/Home/WelcomeMsg";
        var name = $('#Name').val();
        $.get(url, { input: name }, function (data) {
            $("#rData").html(data);
        });
    })
</script>
}

<div class="row">
    <h2 dir="rtl"> קצת עלינו</h2>
    <p dir="rtl">האתר שלנו משרת את המטייל הישראלי, לפני שסוגרים חופשה בחו"ל צריך לדאוג למלון טוב שיענה על הדרישות ויספק אותנו בחופשה הבאה</p>
    <p dir="rtl">כמו כן, ישראלים רבים שומרי הכשרות לא יצטרכו לטרוח כ"כ בחיפוש אחר מסעדות כשרות בחו"ל, אצלנו באתר המסעדות הידועות והטובות מוגשות למטייל הישראלי</p>
    <p dir="rtl">כל מה שעליכם לעשות הוא רק לחפש לפי היעד המבוקש בכל אחד מהאזורים באתר, כמו כן, אתם יכולים להירשם לאתר שלנו</p>
    <p dir="rtl">לקבל מידע שוטף ולאחר הטיול שלכם, תוכלו להמליץ לאחרים ולתת ביקורת משלכם על המלון שהייתם או המסעדות שאכלתם בהם ולשתף אחרים</p>

</div>
 <!-- image of the web developers -->
    <div class="section">
        <div class="container">
            <h2 dir="rtl">דבר העורכים</h2>
            <div class="row">
                <!-- start of image  -->
                <div class="testimonial col-md-4 col-sm-6">
                    <!-- Author Photo -->
                    <div class="author-photo">
                        <img src="~/img/roi.png" alt="Author 1" width="10" height="10">
                    </div>
                    <div class="testimonial-bubble">
                        <blockquote>
                            <!-- Quote -->
                            <p class="quote" dir="rtl">
                                "האתר ידידותי מאוד, המטרה היתה להקל על המטייל הישראלי בחיפושים אחרי מסעדות כשרות ומלונות ברמה גבוהה"
                            </p>                       
                        </blockquote>
                        <cite class="author-info">
                            ROI SIBONI
                        </cite>
                        <div class="sprite arrow-speech-bubble"></div>
                    </div>
                </div>
                <div class="testimonial col-md-4 col-sm-6">
                    <div class="author-photo">
                        <img src="~/img/or1.png" alt="Author 2">
                    </div>
                    <div class="testimonial-bubble">
                        <blockquote>
                            <p class="quote" dir="rtl"> 
                                "חשוב מאוד שכל מטייל יפיק את המירב מהחופשה שלו והבסיס לכל חופשה טובה זה נוחות ומיקום לינה נגיש לאזורים האטרקטיביים"
                            </p>
                           
                        </blockquote>
                        <cite class="author-info">
                            OR TAL
                        </cite>
                        <div class="sprite arrow-speech-bubble"></div>
                    </div>
                </div>
                <div class="testimonial col-md-4 col-sm-6">
                    <div class="author-photo">
                        <img src="~/img/rotem.png" alt="Author 3">
                    </div>
                    <div class="testimonial-bubble">
                        <blockquote>
                            <p class="quote" dir="rtl">
                                "המטרה שהצבנו לעצמנו היתה לעשות לישראלי חיים קלים יותר בחיפוש אחרי מלון טוב, האתר יהיה יעיל יותר בהמשך עם ערכים נוספים שיקלו על תכנון הטיול "
                            </p>
                            <cite class="author-info">
                                ROTEM MOR
                            </cite>
                        </blockquote>
                        <div class="sprite arrow-speech-bubble"></div>
                    </div>
                </div>
                <!-- End of image -->

            </div>
        </div>
    </div>


<footer>
    <section>
        <div id="about">
         כל הזכויות שמורות למפתחי האתר - רועי סיבוני, אור טל ורותם מור   &copy;
        </div>
    </section>
</footer>

proj1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<img src="http://srv1.jpg.co.il/4/558421b8900ec.png" alt="כותרת 1">

 <!-- aside in home page -->
<aside>
    <div class="col-md-4">
        <div class="well">
            <h4 dir="rtl">יש לך יעד לטיול? דאגנו לך למלון טוב-הכנס לאחת האופציות ורשום את יעד הטיול שלך</h4>
            <hr />
            <div class="row">
                <div>
                    <ul class="list-unstyled">
                        <li>
                          <b>@Html.ActionLink("צפה בהמלצות הגולשים על מאגר המסעדות", "Index", "RecommendationRests")</b>
                        </li>
                        <li>
                            <b>@Html.ActionLink("צפה בהמלצות הגולשים על מאגר המלונות", "Index", "RecommendationHotels")</b>
                        </li>                    
                    </ul>
                </div>               
            </div>         
        </div>
        <!-- Side Widget Well -->
        <div class="well">
            <h4 dir="rtl">עושים לך פחות כאב ראש!</h4>
            <p dir="rtl">הכי חשוב לישראלי שהמלון יהיה קרוב להכל, שבטיול שלו יהיה אוכל טוב בלי להיסחב עם "אוכל מהבית" ולהשאיר את המנה החמה בארון.</p>
            <p dir="rtl">באתר שלנו קיבצנו עבור הישראלי המטייל את המלונות הנוחים והטובים ביותר ומסעדות במחיר סביר ,אוכל טוב והכי חשוב.. בטעם של בית</p>
        </div>
    </div>
</aside>

<!--video tag-->
<video autoplay id="bgvid">
    <source src="~/Content/A_Day_in_Barcelona.webm" type="video/webm">
    <source src="~/Content/A_Day_in_Barcelona.mp4" type="video/mp4">
</video>

<!--box in home page-->
<div id="polina">
    <h1>-המלצת השבוע - טיול בברצלונה</h1>
    <p>
    <p>לפי סקר שנערך באתר עולה כי ישנה עליה באחוז המייטלים בברצלונה, ישראלים רבים מחפשים מלונות,מסעדות כשרות וכדומה</p>
    <p>האתר שלנו עוזר לכם לקבל המלצות על המקומות הכי טובים בעולם כמובן לפי הצרכים של הישראלי היפה</p>
    @Html.ActionLink("לחץ כאן וחפש לך מלון", "Index", "Hotels")
    <button>עצור קליפ</button>
</div>

<!--script video-->
<script>
    var vid = document.getElementById("bgvid");
    var pauseButton = document.querySelector("#polina button");

    function vidFade() {
        vid.classList.add("stopfade");
    }

    vid.addEventListener('ended', function () {
        // only functional if "loop" is removed
        vid.pause();
        // to capture IE10
        vidFade();
    });


    pauseButton.addEventListener("click", function () {
        vid.classList.toggle("stopfade");
        if (vid.paused) {
            vid.play();
            pauseButton.innerHTML = "Pause";
        } else {
            vid.pause();
            pauseButton.innerHTML = "Paused";
        }
    })

</script>